name: 'secure_system__dbt_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'secure_system__dbt_project'

# These configurations specify where dbt should look for different types of files.
# For Databricks asset bundles, we put everything in src, as you may have
# non-dbt resources in your project.
model-paths: ["src/models"]
analysis-paths: ["src/analyses"]
test-paths: ["src/tests"]
seed-paths: ["src/seeds"]
macro-paths: ["src/macros"]
snapshot-paths: ["src/snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views by default. These settings can be overridden in the
# individual model files using the `{{ config(...) }}` macro.
seeds:
  secure_system__dbt_project:
    +database: "{{ 'intuitas_admin' if target.name == 'prod' else 'intuitas_admin_test' if target.name == 'test' else 'intuitas_admin_dev' }}"   # Different catalog for seeds depending on environment
    +schema: ref 

models:
  secure_system__dbt_project:
    # Config indicated by + and applies to all files under models/example/
    secure_system:
      +database: "{{ 'secure_system ' if target.name == 'prod' else 'secure_system_test' if target.name == 'test' else 'secure_system_dev' }}"   # Different catalog for seeds depending on environment
      +materialized: view
      access:
        +materialized: view
        +schema: access
      billing:
        +materialized: view
        +schema: billing
      compute:
        +materialized: view
        +schema: compute
      lakeflow:
        +materialized: view
        +schema: lakeflow
